permalink: /:categories/:title.html
url: "http://pasindud.github.io/jekyll-masonry/"
full_name: "Copeyright your momm"
first_name: "A."
last_name: "K."
blog_title: "AK"
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "AK"
copyright_year: "2014"
google_analytics_code: ""
aboutme: "Internet is awesome"
kicker: "inject a little love"
twitter: "berserk_panda"
github: "antonkostiuchkov"
facebook: "antonkostiuchkov"
linkined_url: ""
